pip install tensorboard;
pip install thop;
pip install monai==0.5.0;
pip install matplotlib;
pip install medpy;
pip install opencv-python;
pip install timm==0.6.13;
pip install numpy==1.23.0
pip install scikit-image;
pip install ml_collections;
pip install einops;
pip install batchgenerators;
pip install h5py;
pip install nibabel;
pip install urlrequest;
pip install torchmetrics;
pip install pretrainedmodels;
pip install efficientnet_pytorch;